export const products = [
  { id: "excavator", name: "挖掘机", aliases: ["挖掘机", "挖机", "液压挖掘机"] },
  { id: "loader", name: "装载机", aliases: ["装载机", "铲车"] },
  { id: "truck_crane", name: "汽车起重机", aliases: ["汽车起重机", "汽车吊"] },
  { id: "crawler_crane", name: "履带起重机", aliases: ["履带起重机", "履带吊"] },
  { id: "tower_crane", name: "塔式起重机", aliases: ["塔式起重机", "塔机"] },
  { id: "forklift", name: "叉车", aliases: ["叉车", "工业车辆"] },
  { id: "bulldozer", name: "推土机", aliases: ["推土机"] },
  { id: "roller", name: "压路机", aliases: ["压路机", "道路机械"] },
  { id: "port_machine", name: "港机", aliases: ["港机", "港口机械", "集装箱起重机"] },
  { id: "aerial_platform", name: "高空作业平台", aliases: ["高空作业平台", "高机", "升降工作平台"] },
  { id: "concrete_machine", name: "混凝土机械", aliases: ["混凝土机械", "泵车", "搅拌车", "混凝土泵"] },
  { id: "pile_machine", name: "桩工机械", aliases: ["桩工机械", "旋挖钻机", "打桩机"] },
  { id: "grader", name: "平地机", aliases: ["平地机"] },
  { id: "scraper", name: "铲运机", aliases: ["铲运机", "铲运车"] },
];

export const companies = [
  {
    code: "600031",
    name: "三一重工",
    market: "A股",
    cninfo: { stock: "600031,gssh0600031", column: "sse", plate: "sh" },
    url: "https://www.cninfo.com.cn/new/disclosure/stock?stockCode=600031&orgId=gssh0600031",
  },
  {
    code: "000157",
    name: "中联重科",
    market: "A股/H股",
    cninfo: { stock: "000157,gssz0000157", column: "szse", plate: "sz" },
    hkexCode: "01157",
    url: "https://www.cninfo.com.cn/new/disclosure/stock?stockCode=000157&orgId=gssz0000157",
  },
  {
    code: "000425",
    name: "徐工机械",
    market: "A股",
    cninfo: { stock: "000425,gssz0000425", column: "szse", plate: "sz" },
    url: "https://www.cninfo.com.cn/new/disclosure/stock?stockCode=000425&orgId=gssz0000425",
  },
  {
    code: "000528",
    name: "柳工",
    market: "A股",
    cninfo: { stock: "000528,gssz0000528", column: "szse", plate: "sz" },
    aliases: ["柳工机械"],
    url: "https://www.cninfo.com.cn/new/disclosure/stock?stockCode=000528&orgId=gssz0000528",
  },
  {
    code: "000680",
    name: "山推股份",
    market: "A股",
    cninfo: { stock: "000680,gssz0000680", column: "szse", plate: "sz" },
    url: "https://www.cninfo.com.cn/new/disclosure/stock?stockCode=000680&orgId=gssz0000680",
  },
  {
    code: "002097",
    name: "山河智能",
    market: "A股",
    cninfo: { stock: "002097,gssz0002097", column: "szse", plate: "sz" },
    url: "https://www.cninfo.com.cn/new/disclosure/stock?stockCode=002097&orgId=gssz0002097",
  },
  {
    code: "601100",
    name: "恒立液压",
    market: "A股",
    cninfo: { stock: "601100,gssh0601100", column: "sse", plate: "sh" },
    url: "https://www.cninfo.com.cn/new/disclosure/stock?stockCode=601100&orgId=gssh0601100",
  },
  {
    code: "603638",
    name: "艾迪精密",
    market: "A股",
    cninfo: { stock: "603638,gssh0603638", column: "sse", plate: "sh" },
    url: "https://www.cninfo.com.cn/new/disclosure/stock?stockCode=603638&orgId=gssh0603638",
  },
  {
    code: "603338",
    name: "浙江鼎力",
    market: "A股",
    cninfo: { stock: "603338,gssh0603338", column: "sse", plate: "sh" },
    url: "https://www.cninfo.com.cn/new/disclosure/stock?stockCode=603338&orgId=gssh0603338",
  },
  {
    code: "00631",
    name: "三一国际",
    market: "H股",
    hkexCode: "00631",
    url: "https://www1.hkexnews.hk/search/titlesearch.xhtml?lang=zh",
  },
  {
    code: "03339",
    name: "中国龙工",
    market: "H股",
    hkexCode: "03339",
    aliases: ["龙工"],
    url: "https://www1.hkexnews.hk/search/titlesearch.xhtml?lang=zh",
  },
  {
    code: "000338",
    name: "潍柴动力",
    market: "A股/H股",
    cninfo: { stock: "000338,gssz0000338", column: "szse", plate: "sz" },
    hkexCode: "02338",
    url: "https://www.cninfo.com.cn/new/disclosure/stock?stockCode=000338&orgId=gssz0000338",
  },
  {
    code: "301039",
    name: "中集车辆",
    market: "A股/H股",
    cninfo: { stock: "301039,9900039661", column: "szse", plate: "sz" },
    hkexCode: "01839",
    url: "https://www.cninfo.com.cn/new/disclosure/stock?stockCode=301039&orgId=9900039661",
  },
  {
    code: "600761",
    name: "安徽合力",
    market: "A股",
    cninfo: { stock: "600761,gssh0600761", column: "sse", plate: "sh" },
    aliases: ["合力"],
    url: "https://www.cninfo.com.cn/new/disclosure/stock?stockCode=600761&orgId=gssh0600761",
  },
  {
    code: "603298",
    name: "杭叉集团",
    market: "A股",
    cninfo: { stock: "603298,gssh0603298", column: "sse", plate: "sh" },
    aliases: ["杭叉"],
    url: "https://www.cninfo.com.cn/new/disclosure/stock?stockCode=603298&orgId=gssh0603298",
  },
];

export const topicKeywords = [
  "工程机械",
  "装备",
  "设备更新",
  "更新改造",
  "基建",
  "基础设施",
  "重大项目",
  "专项债",
  "交通",
  "水利",
  "铁路",
  "公路",
  "港口",
  "矿山",
  "房地产",
  "固定资产投资",
  "制造业",
  "技改",
  "安全生产",
  "应急",
  "进出口",
  "出口",
  "进口",
  "销量",
  "开工率",
  "作业小时",
  "库存",
  "钢材",
  "液压",
  "发动机",
  ...products.flatMap((item) => item.aliases),
  ...companies.flatMap((item) => [item.name, item.code, item.hkexCode, ...(item.aliases ?? [])]).filter(Boolean),
];

export const topics = [
  {
    id: "central-ndrc",
    name: "发改委",
    board: "industry",
    group: "中央政策",
    url: "https://www.ndrc.gov.cn/xxgk/zcfb/",
    description: "宏观、投资、重大项目和设备更新政策",
  },
  {
    id: "central-miit",
    name: "工信部",
    board: "industry",
    group: "中央政策",
    url: "https://www.miit.gov.cn/zwgk/zcwj/index.html",
    description: "装备制造、制造业技改和产业政策",
  },
  {
    id: "central-mof",
    name: "财政部",
    board: "industry",
    group: "中央政策",
    url: "https://www.mof.gov.cn/zhengwuxinxi/zhengcefabu/",
    description: "专项债、财政支持和税费政策",
  },
  {
    id: "central-mot",
    name: "交通运输部",
    board: "industry",
    group: "中央政策",
    url: "https://xxgk.mot.gov.cn/zhengce/740/826/iframe_list_7232_18.html",
    description: "公路、港口、物流和交通投资政策",
  },
  {
    id: "central-mnr",
    name: "自然资源部",
    board: "industry",
    group: "中央政策",
    url: "https://gk.mnr.gov.cn/",
    description: "矿山、土地、国土空间和资源政策",
  },
  {
    id: "central-mem",
    name: "应急管理部",
    board: "industry",
    group: "中央政策",
    url: "https://www.mem.gov.cn/gk/zfxxgkpt/fdzdgknr/",
    description: "安全生产、应急装备和矿山安全政策",
  },
  {
    id: "province-shandong",
    name: "山东",
    board: "industry",
    group: "地方政策",
    url: "http://www.shandong.gov.cn/col/col94091/index.html",
    description: "重点基建大省政策",
  },
  {
    id: "province-jiangsu",
    name: "江苏",
    board: "industry",
    group: "地方政策",
    url: "https://www.jiangsu.gov.cn/col/col64797/index.html",
    description: "重点基建大省政策",
  },
  {
    id: "province-guangdong",
    name: "广东",
    board: "industry",
    group: "地方政策",
    url: "https://www.gd.gov.cn/zwgk/wjk/",
    description: "重点基建大省政策",
  },
  {
    id: "province-sichuan",
    name: "四川",
    board: "industry",
    group: "地方政策",
    url: "https://www.sc.gov.cn/10462/c110518/list_ft.shtml",
    description: "重点基建大省政策",
  },
  {
    id: "province-henan",
    name: "河南",
    board: "industry",
    group: "地方政策",
    url: "https://www.henan.gov.cn/zwgk/",
    description: "重点基建大省政策",
  },
  {
    id: "province-hubei",
    name: "湖北",
    board: "industry",
    group: "地方政策",
    url: "https://www.hubei.gov.cn/zfwj/",
    description: "重点基建大省政策",
  },
  {
    id: "province-zhejiang",
    name: "浙江",
    board: "industry",
    group: "地方政策",
    url: "https://www.zj.gov.cn/col/col1229017138/index.html",
    description: "重点基建大省政策",
  },
  {
    id: "province-hebei",
    name: "河北",
    board: "industry",
    group: "地方政策",
    url: "https://www.hebei.gov.cn/",
    description: "重点基建大省政策",
  },
  {
    id: "official-data",
    name: "权威数据",
    board: "industry",
    group: "行业数据",
    url: "https://www.stats.gov.cn/sj/",
    description: "统计局、海关、协会和行业媒体数据",
  },
  {
    id: "trade-data",
    name: "进出口",
    board: "industry",
    group: "行业数据",
    url: "https://www.customs.gov.cn/customs/302249/zfxxgk/2799825/302274/index.html",
    description: "海关总署进出口数量、金额、价格与增速",
  },
  {
    id: "association-data",
    name: "协会数据",
    board: "industry",
    group: "行业数据",
    url: "http://www.cncma.org/",
    description: "中国工程机械工业协会行业统计",
  },
  ...companies.map((company) => ({
    id: `company-${company.code}`,
    name: company.name,
    board: "company",
    group: company.market,
    url: company.url,
    description: `${company.name}公告与经营动态`,
  })),
];

export const sources = [
  {
    id: "ndrc-policy",
    name: "发改委政策发布",
    board: "industry",
    type: "html",
    sourceType: "central_policy",
    url: "https://www.ndrc.gov.cn/xxgk/zcfb/",
    topicIds: ["central-ndrc"],
  },
  {
    id: "miit-policy",
    name: "工信部政策文件",
    board: "industry",
    type: "html",
    sourceType: "central_policy",
    url: "https://www.miit.gov.cn/zwgk/zcwj/index.html",
    topicIds: ["central-miit"],
  },
  {
    id: "mof-policy",
    name: "财政部政策发布",
    board: "industry",
    type: "html",
    sourceType: "central_policy",
    url: "https://www.mof.gov.cn/zhengwuxinxi/zhengcefabu/",
    topicIds: ["central-mof"],
  },
  {
    id: "mot-policy",
    name: "交通运输部政策",
    board: "industry",
    type: "html",
    sourceType: "central_policy",
    url: "https://xxgk.mot.gov.cn/zhengce/740/826/iframe_list_7232_18.html",
    topicIds: ["central-mot"],
  },
  {
    id: "mnr-policy",
    name: "自然资源部政策",
    board: "industry",
    type: "html",
    sourceType: "central_policy",
    url: "https://www.mnr.gov.cn/gk/tzgg/",
    topicIds: ["central-mnr"],
  },
  {
    id: "mem-policy",
    name: "应急管理部公开",
    board: "industry",
    type: "html",
    sourceType: "central_policy",
    url: "https://www.mem.gov.cn/gk/zfxxgkpt/fdzdgknr/",
    topicIds: ["central-mem"],
  },
  {
    id: "shandong-policy",
    name: "山东省政策",
    board: "industry",
    type: "html",
    sourceType: "local_policy",
    url: "http://www.shandong.gov.cn/col/col94091/index.html",
    topicIds: ["province-shandong"],
  },
  {
    id: "jiangsu-policy",
    name: "江苏省政策",
    board: "industry",
    type: "html",
    sourceType: "local_policy",
    url: "https://www.jiangsu.gov.cn/col/col64797/index.html",
    topicIds: ["province-jiangsu"],
  },
  {
    id: "guangdong-policy",
    name: "广东省政策",
    board: "industry",
    type: "html",
    sourceType: "local_policy",
    url: "https://www.gd.gov.cn/zwgk/wjk/",
    topicIds: ["province-guangdong"],
  },
  {
    id: "sichuan-policy",
    name: "四川省政策",
    board: "industry",
    type: "html",
    sourceType: "local_policy",
    url: "https://www.sc.gov.cn/10462/c110518/list_ft.shtml",
    topicIds: ["province-sichuan"],
  },
  {
    id: "henan-policy",
    name: "河南省政务公开",
    board: "industry",
    type: "html",
    sourceType: "local_policy",
    url: "https://www.henan.gov.cn/zwgk/",
    topicIds: ["province-henan"],
  },
  {
    id: "hubei-policy",
    name: "湖北省政府文件",
    board: "industry",
    type: "html",
    sourceType: "local_policy",
    url: "https://www.hubei.gov.cn/zfwj/",
    topicIds: ["province-hubei"],
  },
  {
    id: "zhejiang-policy",
    name: "浙江省政策文件",
    board: "industry",
    type: "html",
    sourceType: "local_policy",
    url: "https://www.zj.gov.cn/col/col1229017138/index.html",
    topicIds: ["province-zhejiang"],
  },
  {
    id: "hebei-policy",
    name: "河北省政府",
    board: "industry",
    type: "html",
    sourceType: "local_policy",
    url: "https://www.hebei.gov.cn/",
    topicIds: ["province-hebei"],
  },
  {
    id: "stats-data",
    name: "国家统计局数据发布",
    board: "industry",
    type: "html",
    sourceType: "official_data",
    url: "https://www.stats.gov.cn/sj/zxfb/",
    topicIds: ["official-data"],
  },
  {
    id: "customs-data",
    name: "海关总署统计数据",
    board: "industry",
    type: "html",
    sourceType: "official_data",
    url: "https://www.customs.gov.cn/customs/302249/zfxxgk/2799825/302274/index.html",
    topicIds: ["trade-data"],
  },
  {
    id: "cncma",
    name: "中国工程机械工业协会",
    board: "industry",
    type: "html",
    sourceType: "association",
    url: "http://www.cncma.org/",
    topicIds: ["association-data"],
  },
  {
    id: "d1cm",
    name: "第一工程机械网",
    board: "industry",
    type: "html",
    sourceType: "industry_media",
    url: "https://news.d1cm.com/",
    topicIds: ["association-data", "official-data"],
  },
  {
    id: "cls",
    name: "财联社",
    board: "industry",
    type: "html",
    sourceType: "finance_media",
    url: "https://www.cls.cn/",
    topicIds: ["official-data"],
  },
  {
    id: "yicai",
    name: "第一财经",
    board: "industry",
    type: "html",
    sourceType: "finance_media",
    url: "https://www.yicai.com/news/",
    topicIds: ["official-data"],
  },
  {
    id: "hkex-latest",
    name: "香港交易所披露易",
    board: "company",
    type: "html",
    sourceType: "exchange_disclosure",
    url: "https://www1.hkexnews.hk/r.php?locale=zh_CN",
    topicIds: companies.filter((item) => item.hkexCode).map((item) => `company-${item.code}`),
  },
  {
    id: "cninfo",
    name: "巨潮资讯网",
    board: "company",
    type: "cninfo",
    sourceType: "exchange_disclosure",
    url: "https://www.cninfo.com.cn/new/commonUrl?url=disclosure/list/notice",
    topicIds: companies.filter((item) => item.cninfo).map((item) => `company-${item.code}`),
  },
];
